[project]
name = "syft-rpc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "cbor2>=5.6.5",
    "pydantic>=2.9.2",
    "python-ulid>=3.0.0",
    "syft-core",
    "typing-extensions>=4.12.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
syft-core = { workspace = true }
