[project]
name = "syftbox-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.114.0",
    "uvicorn>=0.30.6",
    "syftbox-lib",
]

[tool.uv.sources]
syftbox-lib = { path = "../lib", editable = true }
