[project]
name = "syft-proxy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["fastapi>=0.115.5", "syft-event", "syft-rpc", "syft-core"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
syft-rpc = { workspace = true }
syft-event = { workspace = true }
syft-core = { workspace = true }
