[project]
name = "syft-event"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pathspec>=0.12.1",
    "pydantic>=2.9.2",
    "watchdog>=5.0.3",
    "syftbox>=0.2.10",
    "syft-rpc",
]

[tool.uv.sources]
syft-rpc = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
