name: Apps Tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  standalone-apps-tests:
    strategy:
      max-parallel: 99
      matrix:
        include:
          - app: OpenMined/ring
            branch: main
          - app: OpenMined/tutorial-apps
            branch: basic_aggregator
          - app: OpenMined/tutorial-apps
            branch: pretrained_model_aggregator
          - app: OpenMined/tutorial-apps
            branch: pretrained_model_local
        python-version: ["3.9"]
        runner: [syftbox-sh-linux-x64, sh-macos-arm64]
      fail-fast: true

    runs-on: ${{ matrix.runner }}
    steps:
      - name: Cloning the app
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.app }}
          ref: ${{ matrix.branch }}
          path: ${{ matrix.app }}_${{ matrix.branch }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.25"

      - name: Set up Python ${{ matrix.python-version }}
        if: startsWith(matrix.runner, 'syftbox-sh-linux')
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # challenge here is actions/setup-python@v5 requires write access to /Users/runner/hostedtoolcache
      # but current custom macos runner does not allow writing to that dir (even sudo won't work)
      # so we need to use this weird way to install python on macos
      - name: Set up Python ${{ matrix.python-version }} (uv managed)
        if: startsWith(matrix.runner, 'sh-macos')
        run: |
          uv python install ${{ matrix.python-version }}
          uv venv --python ${{ matrix.python-version }} .venv${{ matrix.python-version }}
          uv tool update-shell
          source $HOME/.profile
          source .venv${{ matrix.python-version }}/bin/activate

      - name: Provisioning dummy config
        working-directory: ${{ matrix.app }}
        run: |
          CONFIG_PATH="$(pwd)/config.json"
          SYNC_FOLDER="$(pwd)/syftbox-data/"
          echo '{
              "config_path": "'"$CONFIG_PATH"'",
              "sync_folder": "'"$SYNC_FOLDER"'",
              "port": 8011,
              "email": "alice@openmined.org",
              "token": null,
              "server_url": "http://localhost:5001",
              "email_token": null,
              "autorun_plugins": [
                  "init",
                  "create_datasite",
                  "sync",
                  "apps"
              ]
          }' > $CONFIG_PATH
          cat $CONFIG_PATH

      - name: Run the test
        working-directory: ${{ matrix.app }}
        run: |
          chmod +x ./run.sh
          export SYFTBOX_CLIENT_CONFIG_PATH="$(pwd)/config.json"
          sh ./run.sh
