name: Deploy Stage

on:
  # todo - pr temporary
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      build:
        description: Deploy build from
        type: choice
        default: local
        options:
          - local
          - pypi

      version:
        description: SyftBox version to deploy if above is "pypi"
        type: string
        default: 0.1.12

      dryrun:
        description: Dry Run. Will not deploy to server.
        type: boolean
        # todo - temporarly flipped to true
        default: true

# Prevents concurrent runs of the same workflow
# while the previous run is still in progress
concurrency:
  group: deploy-syftbox-stage
  cancel-in-progress: false

jobs:
  deploy-syftbox-stage:
    # runs-on: ubuntu-latest
    runs-on: syftbox-sh-linux-x64

    steps:
      - name: Install Git & SSH
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install git openssh-client -y

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.25"

      - name: Checkout SyftBox repo
        uses: actions/checkout@v4

      - name: Install Just
        uses: extractions/setup-just@v2
        with:
          just-version: "1.36.0"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SYFTBOX_STAGE_PRIVATE_KEY }}" > ~/.ssh/cert.pem
          chmod 600 ~/.ssh/cert.pem
          ssh-keyscan -H "4.227.144.171" >> ~/.ssh/known_hosts

      - name: Test Conditional
        run: |
          echo "Build: ${{ inputs.build }}"
          echo "Version: ${{ inputs.version }}"
          echo "Dry Run: ${{ inputs.dryrun }}"
          echo "Event Name: ${{ github.event_name }}"
      
      - name: Test If conditional
        if: ${{ inputs.dryrun == false }} && ${{ inputs.build == 'local' }} && github.event_name != 'pull_request'
        run: |
          echo "Deploying SyftBox (Local Wheel Build)"

      - name: Test if conditional pass 2
        if: ${{ inputs.dryrun == false  && inputs.build == 'pypi'  && github.event_name != 'pull_request' }}
        run: |
          echo "Pass 2: Deploying SyftBox (Local Wheel Build)"

      # - name: Deploy SyftBox (Local Wheel Build)
      #   if: ${{ inputs.dryrun == false }} && ${{ inputs.build == 'local' }} && github.event_name != 'pull_request'
      #   run: |
      #     just upload-dev ~/.ssh/cert.pem azureuser@4.227.144.171

      # - name: Deploy SyftBox (PyPI ${{ inputs.version }})
      #   if: ${{ inputs.dryrun == false }} && ${{ inputs.build == 'pypi' }} && github.event_name != 'pull_request'
      #   run: |
      #     just upload-pip ${{ inputs.version }} ~/.ssh/cert.pem azureuser@4.227.144.171

      - name: Delete cert.pem
        if: always()
        run: |
          rm -f ~/.ssh/cert.pem
