name: CD - SyftBox

on:
  schedule:
    - cron: "0 12 * * 0" # At 12:00 UTC on every Sunday

  workflow_dispatch:
    inputs:
      none:
        description: "Run SyftBox CD workflow"
        required: false

# Prevents concurrent runs of the same workflow
# while the previous run is still in progress
concurrency:
  group: "CD - SyftBox"
  cancel-in-progress: false

jobs:
  deploy-syftbox:
    runs-on: ubuntu-latest
    permissions:
      contents: write # For tag and release notes.

    steps:
      - name: Permission to home directory
        run: |
          sudo chown -R $USER:$USER $HOME

      - name: Checkout SyftBox repo with github token
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SYFTBOX_BOT_COMMIT_TOKEN }}

      # free 10GB of space
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          docker image prune --all --force
          docker builder prune --all --force
          docker system prune --all --force

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv==0.4.1
          uv --version

      - name: Install Just
        uses: extractions/setup-just@v2
        with:
          just-version: '1.36.0'

      - name: Bump the Version
        run: |
          just bump-version patch
      
      - name: Build the New Vesrion
        run: |
          just build

      - name: Push to https://pypi.org/
        run: |
          twine upload -u __token__ -p ${{ secrets.OM_SYFTBOX_PYPI_TOKEN }} dist/*

      - name: Push changes to SyftBox repo
        run : |
          git config user.name "${{ secrets.OM_BOT_NAME }}"
          git config user.email "${{ secrets.OM_BOT_EMAIL }}"
          git push origin main

    # todo: maybe add github release here