name: E2E Tests

on:
  workflow_dispatch:

  workflow_call:

  pull_request:
    branches:
      - main

concurrency:
  group: e2e-tests
  cancel-in-progress: true

jobs:
  e2e-tests:
    strategy:
      max-parallel: 99
      matrix:
        # os: [ubuntu-latest, macos-latest]
        runner: [syftbox-sh-linux-x64, sh-macos-arm64]
        python-version: ["3.9", "3.12"]
        e2e-test: ["ring"]
      fail-fast: false

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.25"

      - name: Install Just
        uses: extractions/setup-just@v2
        with:
          just-version: "1.36.0"

      - name: "Setup jq"
        uses: dcarbone/install-jq-action@v2
        with:
          version: "1.7"

      - name: Set up Python ${{ matrix.python-version }}
        if: startsWith(matrix.runner, 'syftbox-sh-linux')
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # challenge here is actions/setup-python@v5 requires write access to /Users/runner/hostedtoolcache
      # but current custom macos runner does not allow writing to that dir (even sudo won't work)
      # so we need to use this weird way to install python on macos
      - name: Set up Python ${{ matrix.python-version }} (uv managed)
        if: startsWith(matrix.runner, 'sh-macos')
        run: |
          uv python install ${{ matrix.python-version }}
          uv venv --python ${{ matrix.python-version }} .venv${{ matrix.python-version }}
          uv tool update-shell
          source $HOME/.profile
          source .venv${{ matrix.python-version }}/bin/activate

      - name: Install SyftBox
        run: |
          uv tool install --upgrade syftbox

      - name: Pre-test checks
        run: |
          uv --version
          jq --version
          just --version
          curl --version
          syftbox version

      - name: Run E2E Test for '${{ matrix.e2e-test }}'
        run: |
          just test-e2e ${{ matrix.e2e-test }}

      - name: Upload e2e directory
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-${{ matrix.e2e-test }}-${{ runner.os }}-${{ matrix.python-version }}
          path: .e2e/${{ matrix.e2e-test }}
