name: PR Tests

on:
  workflow_call:

  pull_request:
    branches:
      - dev
      - main

  workflow_dispatch:
    inputs:
      none:
        description: "Run Tests Manually"
        required: false

concurrency:
  group: syft-${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.event.pull_request.number) || github.workflow_ref }}
  cancel-in-progress: true

jobs:
  pr-tests:
    strategy:
      max-parallel: 99
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.12", "3.11", "3.10"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: "clean .git/config"
        if: matrix.os == 'windows-latest'
        continue-on-error: true
        shell: bash
        run: |
          echo "deleting ${GITHUB_WORKSPACE}/.git/config"
          rm ${GITHUB_WORKSPACE}/.git/config

      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        if: steps.changes.outputs.syft == 'true'
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip packages
        if: steps.changes.outputs.syft == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -U uv tox tox-uv pytest
          uv --version

      - name: Get uv cache dir
        id: pip-cache
        if: steps.changes.outputs.syft == 'true'
        shell: bash
        run: |
          echo "dir=$(uv cache dir)" >> $GITHUB_OUTPUT

      - name: Load github cache
        uses: actions/cache@v4
        if: steps.changes.outputs.syft == 'true'
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-uv-py${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-py${{ matrix.python-version }}-

      - name: Run unit tests
        if: steps.changes.outputs.syft == 'true'
        env:
          TOX_PYTHON: python${{ matrix.python-version }}
        run: |
          tox -e syft.test.unit
